services:
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: unless-stopped
    ports:
      - '8500:8500' # HTTP API and UI
      - '8600:8600/tcp' # DNS
      - '8600:8600/udp' # DNS
      - '8300:8300' # Server RPC
      - '8301:8301' # Serf LAN
      - '8302:8302' # Serf WAN
    volumes:
      - consul-data:/consul/data
      - ./.consul-config:/consul/config
    command: >
      agent -server -ui
      -bootstrap-expect=1
      -node=consul-server
      -client=0.0.0.0
      -bind=0.0.0.0
      -data-dir=/consul/data
      -config-dir=/consul/config
    environment:
      - CONSUL_BIND_INTERFACE=eth0

volumes:
  consul-data:
